const videoData = {
  mainCard: {
    title: 'Эфир с выпускником нашей программы',
    caption: 'Иван Рустаев, выпускник программы',
    link: '/',
    img: './images/video/video-main.jpg',
    altImg: 'Превью видео',
  },
  cards: [
    {
      id: 1,
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 2,
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
    },
    {
      id: 3,
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
    },
    {
      id: 4,
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 5,
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 6,
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
    },
    {
      id: 7,
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
    },
    {
      id: 8,
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 9,
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 10,
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
    },
    {
      id: 11,
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
    },
    {
      id: 12,
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 13,
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 14,
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
    },
    {
      id: 15,
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
    },
    {
      id: 16,
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 17,
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
    {
      id: 18,
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
    },
    {
      id: 19,
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
    },
    {
      id: 20,
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
    },
  ],
};

export default videoData;
