const videoData = {
  tags: ['Ресурсная группа', 'Эксперт', 'Пары', 'События', 'Медиа о нас'],
  cards: [
    {
      id: 1,
      choosingByMentor: true,
      img: './images/video/video-main.jpg',
      altImg: 'Превью видео',
      title: 'Эфир с выпускником нашей программы',
      caption: 'Иван Рустаев, выпускник программы',
      link: '/',
      tag: 'Ресурсная группа',
    },
    {
      id: 2,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
      tag: 'Эксперт',
    },
    {
      id: 3,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
      tag: 'Пары',
    },
    {
      id: 4,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'События',
    },
    {
      id: 5,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Медиа о нас',
    },
    {
      id: 6,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
      tag: 'Ресурсная группа',
    },
    {
      id: 7,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
      tag: 'Эксперт',
    },
    {
      id: 8,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Пары',
    },
    {
      id: 9,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'События',
    },
    {
      id: 10,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
      tag: 'Медиа о нас',
    },
    {
      id: 11,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
      tag: 'Ресурсная группа',
    },
    {
      id: 12,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Эксперт',
    },
    {
      id: 13,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Пары',
    },
    {
      id: 14,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
      tag: 'События',
    },
    {
      id: 15,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
      tag: 'Медиа о нас',
    },
    {
      id: 16,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Ресурсная группа',
    },
    {
      id: 17,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Эксперт',
    },
    {
      id: 18,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-2.png',
      altImg: 'Превью видео',
      title: 'Что в силах волонтера-наставника?',
      caption: 'Иван Рустаев, волонтер-наставник',
      tag: 'Пары',
    },
    {
      id: 19,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-3.png',
      altImg: 'Превью видео',
      title: 'Творчество, наставничество, дети',
      caption: 'Виктория Ямина, Виктория Ямина, волонтеры',
      tag: 'События',
    },
    {
      id: 20,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-4.png',
      altImg: 'Превью видео',
      title: 'Дружба – меняет мир',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Медиа о нас',
    },
    {
      id: 21,
      choosingByMentor: false,
      link: '/',
      img: '../images/video/video-ex-1.png',
      altImg: 'Превью видео',
      title: 'Меняется смысл – меняется жизн',
      caption: 'Прямой эфир с актрисой театра и кино Эмилией Спивак',
      tag: 'Медиа о нас',
    },
  ],
};

export default videoData;
